### PR TITLE
修复分包等问题，一键分包，和举例

### PR DESCRIPTION
**Pull request by larack8**
修复分包等问题，一键分包，和举例

### CODE REVIEW

**Comment by tianbymy** [comment]
Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.

**Comment by larack8** [comment]
修复分包等问题，一键分包，和举例

**Comment by yixuancc** [comment]
> 修复分包等问题，一键分包，和举例

大佬，我这个分包解不出是怎么回事？报这个错
Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.

**Comment by caominkeji** [comment]
wxss解不出来了分包插件的  ReferenceError: __vd_version_info__ is not defined
    at vm.js:3:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (C:\Users\Administrator\Desktop\node1\node_modules\vm2\lib\main.js:204:72)
    at runVM (C:\Users\Administrator\Desktop\node1\wuWxss.js:97:4)
    at runOnce (C:\Users\Administrator\Desktop\node1\wuWxss.js:121:27)
    at Array.preRun (C:\Users\Administrator\Desktop\node1\wuWxss.js:201:5)
    at CntEvent.decount (C:\Users\Administrator\Desktop\node1\wuLib.js:17:43)
    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\node1\wuLib.js:81:11)
    at agent (C:\Users\Administrator\Desktop\node1\wuLib.js:54:14)
    at tryToString (fs.js:513:3)

**Comment by gudqs7** [comment]
> > 修复分包等问题，一键分包，和举例
> 
> 大佬，我这个分包解不出是怎么回事？报这个错
> Error: This package is unrecognizable.
> May be this package is a subPackage which should be unpacked with -s=.
> Otherwise, please decrypted every type of file by hand.

看我的, 实现了 -s 参数, 干实事, 别瞎几把说实现了啥啥, 我还以为真实现了, 一看代码 呵呵
https://github.com/gudqs7/wxappUnpacker

**Comment by NullYing** [comment]
修复作者是别人的bug，并增加收钱二维码？

**Comment by xiaoyouxuxu** [comment]
D:\atest\wxappUnpacker-master\wxappUnpacker-master\wuWxapkg.js:104
        }else throw Error("This package is unrecognizable.\nMay be this package is a subPackage which should be unpacked with -s=<MainDir>.\nOtherwise, please decrypted every type of file by hand.")
              ^

Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.
    at Array.packDone (D:\atest\wxappUnpacker-master\wxappUnpacker-master\wuWxapkg.js:104:14)
    at CntEvent.decount (D:\atest\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:17:43)
    at D:\atest\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:73:11
    at agent (D:\atest\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqCallback.oncomplete (fs.js:146:23)

大神，能给我解答下这个怎么处理吗？感谢，感谢~

**Comment by Traveler-Brian** [comment]
> 修复分包等问题，一键分包，和举例

大佬，解的时候出现了这个是什么原因啊

`=======================================================
vm.js:17
			});
			^

SyntaxError: Unexpected token '}'
    at new Script (vm.js:84:7)
`

**Pull request closed without merging**
